#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mon1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AMIT")]
	public partial class asaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public asaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AMITConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public asaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public asaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public asaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public asaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<asa> asas
		{
			get
			{
				return this.GetTable<asa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.asa")]
	public partial class asa
	{
		
		private int _id;
		
		private string _businessowner;
		
		private string _servername;
		
		private string _ismonitored;
		
		private string _toolname;
		
		private string _whyunmonitored;
		
		private string _environment;
		
		private string _nodetype;
		
		private string _framename;
		
		private string _datacenter;
		
		private string _hardwaremodel;
		
		private string _os;
		
		private string _serialnumber;
		
		private string _servereol;
		
		private System.Nullable<System.DateTime> _installdate;
		
		private System.Nullable<System.DateTime> _lastupdated;
		
		public asa()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_businessowner", DbType="NVarChar(50)")]
		public string businessowner
		{
			get
			{
				return this._businessowner;
			}
			set
			{
				if ((this._businessowner != value))
				{
					this._businessowner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servername", DbType="NVarChar(50)")]
		public string servername
		{
			get
			{
				return this._servername;
			}
			set
			{
				if ((this._servername != value))
				{
					this._servername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ismonitored", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ismonitored
		{
			get
			{
				return this._ismonitored;
			}
			set
			{
				if ((this._ismonitored != value))
				{
					this._ismonitored = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toolname", DbType="VarChar(9)")]
		public string toolname
		{
			get
			{
				return this._toolname;
			}
			set
			{
				if ((this._toolname != value))
				{
					this._toolname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whyunmonitored", DbType="NVarChar(50)")]
		public string whyunmonitored
		{
			get
			{
				return this._whyunmonitored;
			}
			set
			{
				if ((this._whyunmonitored != value))
				{
					this._whyunmonitored = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_environment", DbType="NVarChar(50)")]
		public string environment
		{
			get
			{
				return this._environment;
			}
			set
			{
				if ((this._environment != value))
				{
					this._environment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodetype", DbType="NVarChar(50)")]
		public string nodetype
		{
			get
			{
				return this._nodetype;
			}
			set
			{
				if ((this._nodetype != value))
				{
					this._nodetype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_framename", DbType="NVarChar(50)")]
		public string framename
		{
			get
			{
				return this._framename;
			}
			set
			{
				if ((this._framename != value))
				{
					this._framename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datacenter", DbType="NVarChar(50)")]
		public string datacenter
		{
			get
			{
				return this._datacenter;
			}
			set
			{
				if ((this._datacenter != value))
				{
					this._datacenter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hardwaremodel", DbType="NVarChar(50)")]
		public string hardwaremodel
		{
			get
			{
				return this._hardwaremodel;
			}
			set
			{
				if ((this._hardwaremodel != value))
				{
					this._hardwaremodel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_os", DbType="NVarChar(50)")]
		public string os
		{
			get
			{
				return this._os;
			}
			set
			{
				if ((this._os != value))
				{
					this._os = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serialnumber", DbType="NVarChar(50)")]
		public string serialnumber
		{
			get
			{
				return this._serialnumber;
			}
			set
			{
				if ((this._serialnumber != value))
				{
					this._serialnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servereol", DbType="NVarChar(50)")]
		public string servereol
		{
			get
			{
				return this._servereol;
			}
			set
			{
				if ((this._servereol != value))
				{
					this._servereol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_installdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> installdate
		{
			get
			{
				return this._installdate;
			}
			set
			{
				if ((this._installdate != value))
				{
					this._installdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastupdated
		{
			get
			{
				return this._lastupdated;
			}
			set
			{
				if ((this._lastupdated != value))
				{
					this._lastupdated = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
