#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mon1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Spectrum")]
	public partial class auditDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertaudit(audit instance);
    partial void Updateaudit(audit instance);
    partial void Deleteaudit(audit instance);
    #endregion
		
		public auditDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SpectrumConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public auditDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public auditDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public auditDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public auditDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<audit> audits
		{
			get
			{
				return this.GetTable<audit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.audit")]
	public partial class audit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private System.DateTime _timestamp;
		
		private int _hasbeensent;
		
		private string _ip;
		
		private string _notes;
		
		private string _mhandle;
		
		private string _mname;
		
		private string _manu;
		
		private string _devicetype;
		
		private string _macaddress;
		
		private string _landscape;
		
		private string _hashvalue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OntimestampChanging(System.DateTime value);
    partial void OntimestampChanged();
    partial void OnhasbeensentChanging(int value);
    partial void OnhasbeensentChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    partial void OnmhandleChanging(string value);
    partial void OnmhandleChanged();
    partial void OnmnameChanging(string value);
    partial void OnmnameChanged();
    partial void OnmanuChanging(string value);
    partial void OnmanuChanged();
    partial void OndevicetypeChanging(string value);
    partial void OndevicetypeChanged();
    partial void OnmacaddressChanging(string value);
    partial void OnmacaddressChanged();
    partial void OnlandscapeChanging(string value);
    partial void OnlandscapeChanged();
    partial void OnhashvalueChanging(string value);
    partial void OnhashvalueChanged();
    #endregion
		
		public audit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasbeensent", DbType="Int NOT NULL")]
		public int hasbeensent
		{
			get
			{
				return this._hasbeensent;
			}
			set
			{
				if ((this._hasbeensent != value))
				{
					this.OnhasbeensentChanging(value);
					this.SendPropertyChanging();
					this._hasbeensent = value;
					this.SendPropertyChanged("hasbeensent");
					this.OnhasbeensentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="VarChar(4000)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mhandle", DbType="VarChar(50)")]
		public string mhandle
		{
			get
			{
				return this._mhandle;
			}
			set
			{
				if ((this._mhandle != value))
				{
					this.OnmhandleChanging(value);
					this.SendPropertyChanging();
					this._mhandle = value;
					this.SendPropertyChanged("mhandle");
					this.OnmhandleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mname", DbType="VarChar(50)")]
		public string mname
		{
			get
			{
				return this._mname;
			}
			set
			{
				if ((this._mname != value))
				{
					this.OnmnameChanging(value);
					this.SendPropertyChanging();
					this._mname = value;
					this.SendPropertyChanged("mname");
					this.OnmnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manu", DbType="VarChar(50)")]
		public string manu
		{
			get
			{
				return this._manu;
			}
			set
			{
				if ((this._manu != value))
				{
					this.OnmanuChanging(value);
					this.SendPropertyChanging();
					this._manu = value;
					this.SendPropertyChanged("manu");
					this.OnmanuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devicetype", DbType="VarChar(50)")]
		public string devicetype
		{
			get
			{
				return this._devicetype;
			}
			set
			{
				if ((this._devicetype != value))
				{
					this.OndevicetypeChanging(value);
					this.SendPropertyChanging();
					this._devicetype = value;
					this.SendPropertyChanged("devicetype");
					this.OndevicetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macaddress", DbType="VarChar(50)")]
		public string macaddress
		{
			get
			{
				return this._macaddress;
			}
			set
			{
				if ((this._macaddress != value))
				{
					this.OnmacaddressChanging(value);
					this.SendPropertyChanging();
					this._macaddress = value;
					this.SendPropertyChanged("macaddress");
					this.OnmacaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_landscape", DbType="VarChar(50)")]
		public string landscape
		{
			get
			{
				return this._landscape;
			}
			set
			{
				if ((this._landscape != value))
				{
					this.OnlandscapeChanging(value);
					this.SendPropertyChanging();
					this._landscape = value;
					this.SendPropertyChanged("landscape");
					this.OnlandscapeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hashvalue", DbType="NVarChar(35)")]
		public string hashvalue
		{
			get
			{
				return this._hashvalue;
			}
			set
			{
				if ((this._hashvalue != value))
				{
					this.OnhashvalueChanging(value);
					this.SendPropertyChanging();
					this._hashvalue = value;
					this.SendPropertyChanged("hashvalue");
					this.OnhashvalueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
